name: Build and Deploy to Server

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          
      - run: npm run build
      - name: Upload ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist
  copy:
    name: Copy to dev
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Copy to build branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.PAT }}
          publish_dir: ./dist
          destination_dir: dist
          publish_branch: build
          enable_jekyll: false
          keep_files: false
          commit_message: Build code
  deploy:
    name: Deploy to server
    needs: copy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ${{ secrets.FOLDER }}
            git pull https://${{ secrets.PAT }}@github.com/Fush1ren/ahmed_sam.git build
